from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.login, name='index'),
    path('home/', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('logout_view/', views.logout_view, name='logout_view'),
    path('res/<int:a>/<int:m>/<int:num>/', views.home, name='res'),
    path('dolar/', views.dolar, name='templates/dolar'),
    path('gastacion/', views.gastacion, name='templates/gastacion'),
    path('categorias/', views.categorias, name='templates/categorias'),
    path('gastos/<int:cat>/<int:a>/<int:m>/', views.gastos, name='templates/gastos'),
    path('presupuesto/<int:a>/<int:m>/', views.presupuesto, name='templates/presupuesto'),
    path('presuCategoria/<int:cat>/<int:a>/<int:m>/', views.presuCategoria, name='templates/presuCategoria'),
    path('movimientos/<int:a>/<int:m>/<int:t>', views.movimientos, name='templates/movimientos'),
    path('prodCateg/', views.prodCateg, name='templates/prodCateg2'),
    path('categoria/<int:c>/', views.categoria, name='templates/categoria'),
    path('delete/<int:idMov>/<int:a>/<int:m>/', views.deleteMovimiento),
    path('nuevoMovimiento/<int:t>/', views.nuevoMovimiento, name='templates/nuevoMovimiento'),
    path('guardarMov/', views.guardarMovimento, name='guardarMovimento'),
    path('tck/<int:t>/', views.tck, name='tck'),
    path('guardarItem/',views.guardarItem, name='guardarItem'),
    path('borrarItem/<int:idTemp>/<int:tipo>/', views.borrarItem, name='borrarItem'),
    path('guardarTCK/<int:t>', views.guardarTCK, name='guardarTCK'),
    path('nuevaCategoria/', views.nuevaCategoria, name='nuevaCategoria'),
    path('guardarCategoria/', views.guardarCategoria, name='guardarCategoria'),
    path('nuevoProducto/', views.nuevoProducto, name='nuevoProducto'),
    path('guardarProducto/', views.guardarProducto, name='guardarProducto'),
    path('nuevoComercio/', views.nuevoComercio, name='nuevoComercio'),
    path('guardarComercio/', views.guardarComercio, name='guardarComercio'),
    path('presupuestacion/<str:tipo>/', views.presupuestacion, name='presupuestacion'),
    path('guardarPresupuesto/', views.guardarPresupuesto, name='guardarPresupuesto'),
    path('movilidad/<str:q>/', views.auto, name='auto'),
    path('nuevoCambio/', views.nuevoCambio, name='nuevoCambio'),
    path('guardarCambio/', views.guardarCambio, name='guardarCambio'),
    path('config/<str:t>/', views.config, name='config'),
    path('guardarConfig/', views.guardarConfig, name='guardarConfig'),
    path('deletePersonal/<int:i>/', views.deletePersonal, name='deletePersonal'),
    ]