# Generated by Django 2.1.15 on 2022-01-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ahorros',
            fields=[
                ('idahorro', models.AutoField(db_column='idAhorro', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('anterior', models.FloatField(blank=True, db_column='Anterior', null=True)),
                ('ingreso', models.FloatField(blank=True, db_column='Ingreso', null=True)),
                ('usuario', models.IntegerField(db_column='Usuario')),
                ('ahorro', models.FloatField(blank=True, db_column='Ahorro', null=True)),
            ],
            options={
                'db_table': 'ahorros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idcategoria', models.AutoField(db_column='IdCategoria', primary_key=True, serialize=False)),
                ('categoria', models.CharField(blank=True, db_column='Categoria', max_length=100, null=True)),
                ('tarjeta', models.IntegerField()),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comercios',
            fields=[
                ('idcomercio', models.AutoField(db_column='IdComercio', primary_key=True, serialize=False)),
                ('comercio', models.CharField(blank=True, db_column='Comercio', max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=100, null=True)),
            ],
            options={
                'db_table': 'comercios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('idcotizacion', models.AutoField(db_column='idCotizacion', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('cotizacion', models.FloatField(db_column='Cotizacion')),
            ],
            options={
                'db_table': 'cotizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dolar',
            fields=[
                ('iddolar', models.AutoField(db_column='idDolar', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('cotizacion', models.FloatField(db_column='Cotizacion')),
            ],
            options={
                'db_table': 'dolar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Micambio',
            fields=[
                ('idcambio', models.AutoField(db_column='idCambio', primary_key=True, serialize=False)),
                ('cambio', models.FloatField(db_column='Cambio')),
                ('fecha', models.DateField(db_column='Fecha')),
            ],
            options={
                'db_table': 'micambio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('idmovimiento', models.AutoField(db_column='IdMovimiento', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('comercio', models.IntegerField(blank=True, db_column='Comercio', null=True)),
                ('producto', models.IntegerField(db_column='Producto')),
                ('categoria', models.IntegerField(db_column='Categoria')),
                ('cantidad', models.FloatField(blank=True, db_column='Cantidad', null=True)),
                ('total', models.FloatField(blank=True, db_column='Total', null=True)),
                ('tipo', models.IntegerField(db_column='Tipo')),
                ('adjunto', models.TextField(blank=True, db_column='Adjunto', null=True)),
                ('usuario', models.IntegerField(db_column='Usuario')),
                ('notas', models.TextField(blank=True, db_column='Notas', null=True)),
            ],
            options={
                'db_table': 'movimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.IntegerField()),
                ('categoria', models.IntegerField()),
                ('banco', models.IntegerField()),
            ],
            options={
                'db_table': 'personales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproducto', models.AutoField(db_column='IdProducto', primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(db_column='NombreProducto', max_length=255)),
                ('marca', models.CharField(blank=True, db_column='Marca', max_length=255, null=True)),
                ('categoria', models.IntegerField(db_column='Categoria')),
                ('subcategoria', models.IntegerField(blank=True, db_column='Subcategoria', null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('idsaldo', models.AutoField(db_column='idSaldo', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('saldo', models.FloatField(db_column='Saldo')),
            ],
            options={
                'db_table': 'saldo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField()),
                ('categoria', models.IntegerField()),
            ],
            options={
                'db_table': 'tarjetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('idtipo', models.AutoField(db_column='IdTipo', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=8, null=True)),
            ],
            options={
                'db_table': 'tipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.IntegerField(db_column='Producto')),
                ('categoria', models.IntegerField(db_column='Categoria')),
                ('cantidad', models.FloatField(db_column='Cantidad')),
                ('total', models.FloatField(db_column='Total')),
                ('usuario', models.IntegerField()),
                ('comercio', models.IntegerField()),
            ],
            options={
                'db_table': 'tmp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usercategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField()),
                ('user_categoria', models.IntegerField()),
            ],
            options={
                'db_table': 'usercategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('name_user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=13, null=True)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
                ('permisos_acceso', models.CharField(max_length=11)),
                ('status', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
