# Generated by Django 2.1.15 on 2022-02-27 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fi', '0002_ahorros_categorias_comercios_cotizacion_dolar_micambio_movimientos_personales_productos_saldo_tarjet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'managed': False, 'ordering': ['fecha']},
        ),
        migrations.AlterModelOptions(
            name='movimientos',
            options={'managed': False, 'ordering': ['idmovimiento']},
        ),
        migrations.AlterModelOptions(
            name='personales',
            options={'managed': False, 'ordering': ['idPersonal']},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'managed': False, 'ordering': ['idproducto']},
        ),
        migrations.AlterModelOptions(
            name='usercategoria',
            options={'managed': False, 'ordering': ['userCategoria']},
        ),
    ]
